export enum RequestStatusEnum {
  BTC = 'bitcoin',
  ETH = 'ethereum',
  USDT = 'usdt',
  BNB = 'bnb',
  SOL = 'solana',
  XRP = 'ripple',
  USDC = 'usdc',
  STETH = 'staked-ether',
  ADA = 'cardano',
  AVAX = 'avalanche',
  DOGE = 'dogecoin',
  DOT = 'polkadot',
  TRX = 'tron',
  LINK = 'chainlink',
  TON = 'ton-crystal',
  MATIC = 'matic',
  WBTC = 'wrapped-bitcoin',
  ICP = 'internet-computer',
  SHIB = 'shiba-inu',
  DAI = 'dai',
  LTC = 'litecoin',
  UNI = 'uniswap',
  BCH = 'bitcoin-cash',
  ATOM = 'cosmos',
  ETC = 'ethereum-classic',
  LEO = 'leotoken',
  INJ = 'injective-protocol',
  XLM = 'stellar',
  OP = 'opium',
  NEAR = 'near-protocol',
  OKB = 'okb',
  APT = 'aptoide-token',
  TIA = 'tiacoin',
  LDO = 'lido-dao-token',
  FIL = 'filecoin',
  XMR = 'monero',
  IMX = 'immutable-x',
  HBAR = 'hedera-hashgraph',
  ARB = 'arbitrum',
  KAS = 'kadena',
  CRO = 'crypto-com-coin',
  STX = 'stacks',
  MNT = 'minter',
  VET = 'vechain',
  FDUSD = 'fusedollar',
  SEI = 'serum',
  TUSD = 'trueusd',
  MKR = 'maker',
  QNT = 'quant',
  BSV = 'bitcoin-sv',
  RETH = 'rari-ethereum',
  ORDI = 'orion-protocol',
  GRT = 'the-graph',
  ALGO = 'algorand',
  AAVE = 'aave',
  EGLD = 'elrond',
  RNDR = 'render-token',
  TAO = 'tao-network',
  RUNE = 'thorchain',
  SUI = 'suterusu',
  SATS = 'sats',
  MINA = 'mina-protocol',
  FLOW = 'flow',
  SNX = 'synthetix',
  FTM = 'fantom',
  OSMO = 'osmosis',
  DYDX = 'dydx',
  TKX = 'tokenize-xchange',
  AXS = 'axie-infinity',
  SAND = 'the-sandbox',
  HNT = 'helium',
  THETA = 'theta-network',
  BEAM = 'beam',
  BTT = 'bittorrent',
  XTZ = 'tezos',
  KCS = 'kucoin-token',
  WEMIX = 'wemix',
  CHZ = 'chiliz',
  WBT = 'wrapped-bitcoin-testnet',
  ETHDYDX = 'ethereum-dydx',
  CHEEL = 'cheel',
  EOS = 'eos',
  ASTR = 'astronaut',
  NEO = 'neo',
  BGB = 'bigbom',
  MANA = 'decentraland',
  BONK = 'cryptobunks',
  BLUR = 'blur-network',
  KAVA = 'kava',
  GALA = 'gala',
  ROSE = 'oasis-network',
  KLAY = 'klaytn',
  FRXETH = 'frax-share-ethereum',
  WOO = 'woonkly-power',
  IOTA = 'iota',
  LUNC = 'luna-crush',
  CAKE = 'pancakeswap',
  USDD = 'usdd',
  CFX = 'conflux',
  FET = 'fetch-ai',
}

export enum RequesSymbolEnum {
  BTC = 'btc',
  ETH = 'eth',
  USDT = 'usdt',
  BNB = 'bnb',
  SOL = 'sol',
  XRP = 'xrp',
  USDC = 'usdc',
  STETH = 'steth',
  ADA = 'ada',
  AVAX = 'avax',
  DOGE = 'doge',
  DOT = 'dot',
  TRX = 'trx',
  LINK = 'link',
  TON = 'ton',
  MATIC = 'matic',
  WBTC = 'wbtc',
  ICP = 'icp',
  SHIB = 'shib',
  DAI = 'dai',
  LTC = 'ltc',
  UNI = 'uni',
  BCH = 'bch',
  ATOM = 'atom',
  ETC = 'etc',
  LEO = 'leo',
  INJ = 'inj',
  XLM = 'xlm',
  OP = 'op',
  NEAR = 'near',
  OKB = 'okb',
  APT = 'apt',
  TIA = 'tia',
  LDO = 'ldo',
  FIL = 'fil',
  XMR = 'xmr',
  IMX = 'imx',
  HBAR = 'hbar',
  ARB = 'arb',
  KAS = 'kas',
  CRO = 'cro',
  STX = 'stx',
  MNT = 'mnt',
  VET = 'vet',
  FDUSD = 'fdusd',
  SEI = 'sei',
  TUSD = 'tusd',
  MKR = 'mkr',
  QNT = 'qnt',
  BSV = 'bsv',
  RETH = 'reth',
  ORDI = 'ordi',
  GRT = 'grt',
  ALGO = 'algo',
  AAVE = 'aave',
  EGLD = 'egld',
  RNDR = 'rndr',
  TAO = 'tao',
  RUNE = 'rune',
  SUI = 'sui',
  SATS = 'sats',
  MINA = 'mina',
  FLOW = 'flow',
  SNX = 'snx',
  FTM = 'ftm',
  OSMO = 'osmo',
  DYDX = 'dydx',
  TKX = 'tkx',
  AXS = 'axs',
  SAND = 'sand',
  HNT = 'hnt',
  THETA = 'theta',
  BEAM = 'beam',
  BTT = 'btt',
  XTZ = 'xtz',
  KCS = 'kcs',
  WEMIX = 'wemix',
  CHZ = 'chz',
  WBT = 'wbt',
  ETHDYDX = 'ethdydx',
  CHEEL = 'cheel',
  EOS = 'eos',
  ASTR = 'astr',
  NEO = 'neo',
  BGB = 'bgb',
  MANA = 'mana',
  BONK = 'bonk',
  BLUR = 'blur',
  KAVA = 'kava',
  GALA = 'gala',
  ROSE = 'rose',
  KLAY = 'klay',
  FRXETH = 'frxeth',
  WOO = 'woo',
  IOTA = 'iota',
  LUNC = 'lunc',
  CAKE = 'cake',
  USDD = 'usdd',
  CFX = 'cfx',
  FET = 'fet',
}

export interface ISortCriteria {
  value: string;
  label: RequesSymbolEnum;
  type: RequestStatusEnum;
}

export const sortValues: ISortCriteria[] = [
  {
    value: 'BTC',
    label: RequesSymbolEnum.BTC,
    type: RequestStatusEnum.BTC,
  },
  {
    value: 'ETH',
    label: RequesSymbolEnum.ETH,
    type: RequestStatusEnum.ETH,
  },
  {
    value: 'USDT',
    label: RequesSymbolEnum.USDT,
    type: RequestStatusEnum.USDT,
  },
  {
    value: 'BNB',
    label: RequesSymbolEnum.BNB,
    type: RequestStatusEnum.BNB,
  },
  {
    value: 'SOL',
    label: RequesSymbolEnum.SOL,
    type: RequestStatusEnum.SOL,
  },
  {
    value: 'XRP',
    label: RequesSymbolEnum.XRP,
    type: RequestStatusEnum.XRP,
  },
  {
    value: 'USDC',
    label: RequesSymbolEnum.USDC,
    type: RequestStatusEnum.USDC,
  },
  {
    value: 'STETH',
    label: RequesSymbolEnum.STETH,
    type: RequestStatusEnum.STETH,
  },
  {
    value: 'ADA',
    label: RequesSymbolEnum.ADA,
    type: RequestStatusEnum.ADA,
  },
  {
    value: 'AVAX',
    label: RequesSymbolEnum.AVAX,
    type: RequestStatusEnum.AVAX,
  },
  {
    value: 'DOGE',
    label: RequesSymbolEnum.DOGE,
    type: RequestStatusEnum.DOGE,
  },
  {
    value: 'DOT',
    label: RequesSymbolEnum.DOT,
    type: RequestStatusEnum.DOT,
  },
  {
    value: 'TRX',
    label: RequesSymbolEnum.TRX,
    type: RequestStatusEnum.TRX,
  },
  {
    value: 'LINK',
    label: RequesSymbolEnum.LINK,
    type: RequestStatusEnum.LINK,
  },
  {
    value: 'TON',
    label: RequesSymbolEnum.TON,
    type: RequestStatusEnum.TON,
  },
  {
    value: 'MATIC',
    label: RequesSymbolEnum.MATIC,
    type: RequestStatusEnum.MATIC,
  },
  {
    value: 'WBTC',
    label: RequesSymbolEnum.WBTC,
    type: RequestStatusEnum.WBTC,
  },
  {
    value: 'ICP',
    label: RequesSymbolEnum.ICP,
    type: RequestStatusEnum.ICP,
  },
  {
    value: 'SHIB',
    label: RequesSymbolEnum.SHIB,
    type: RequestStatusEnum.SHIB,
  },
  {
    value: 'DAI',
    label: RequesSymbolEnum.DAI,
    type: RequestStatusEnum.DAI,
  },
  {
    value: 'LTC',
    label: RequesSymbolEnum.LTC,
    type: RequestStatusEnum.LTC,
  },
  {
    value: 'UNI',
    label: RequesSymbolEnum.UNI,
    type: RequestStatusEnum.UNI,
  },
  {
    value: 'BCH',
    label: RequesSymbolEnum.BCH,
    type: RequestStatusEnum.BCH,
  },
  {
    value: 'ATOM',
    label: RequesSymbolEnum.ATOM,
    type: RequestStatusEnum.ATOM,
  },
  {
    value: 'ETC',
    label: RequesSymbolEnum.ETC,
    type: RequestStatusEnum.ETC,
  },
  {
    value: 'LEO',
    label: RequesSymbolEnum.LEO,
    type: RequestStatusEnum.LEO,
  },
  {
    value: 'INJ',
    label: RequesSymbolEnum.INJ,
    type: RequestStatusEnum.INJ,
  },
  {
    value: 'XLM',
    label: RequesSymbolEnum.XLM,
    type: RequestStatusEnum.XLM,
  },
  {
    value: 'OP',
    label: RequesSymbolEnum.OP,
    type: RequestStatusEnum.OP,
  },
  {
    value: 'NEAR',
    label: RequesSymbolEnum.NEAR,
    type: RequestStatusEnum.NEAR,
  },
  {
    value: 'OKB',
    label: RequesSymbolEnum.OKB,
    type: RequestStatusEnum.OKB,
  },
  {
    value: 'APT',
    label: RequesSymbolEnum.APT,
    type: RequestStatusEnum.APT,
  },
  {
    value: 'TIA',
    label: RequesSymbolEnum.TIA,
    type: RequestStatusEnum.TIA,
  },
  {
    value: 'LDO',
    label: RequesSymbolEnum.LDO,
    type: RequestStatusEnum.LDO,
  },
  {
    value: 'FIL',
    label: RequesSymbolEnum.FIL,
    type: RequestStatusEnum.FIL,
  },
  {
    value: 'XMR',
    label: RequesSymbolEnum.XMR,
    type: RequestStatusEnum.XMR,
  },
  {
    value: 'IMX',
    label: RequesSymbolEnum.IMX,
    type: RequestStatusEnum.IMX,
  },
  {
    value: 'HBAR',
    label: RequesSymbolEnum.HBAR,
    type: RequestStatusEnum.HBAR,
  },
  {
    value: 'ARB',
    label: RequesSymbolEnum.ARB,
    type: RequestStatusEnum.ARB,
  },
  {
    value: 'KAS',
    label: RequesSymbolEnum.KAS,
    type: RequestStatusEnum.KAS,
  },
  {
    value: 'CRO',
    label: RequesSymbolEnum.CRO,
    type: RequestStatusEnum.CRO,
  },
  {
    value: 'STX',
    label: RequesSymbolEnum.STX,
    type: RequestStatusEnum.STX,
  },
  {
    value: 'MNT',
    label: RequesSymbolEnum.MNT,
    type: RequestStatusEnum.MNT,
  },
  {
    value: 'VET',
    label: RequesSymbolEnum.VET,
    type: RequestStatusEnum.VET,
  },
  {
    value: 'FDUSD',
    label: RequesSymbolEnum.FDUSD,
    type: RequestStatusEnum.FDUSD,
  },
  {
    value: 'SEI',
    label: RequesSymbolEnum.SEI,
    type: RequestStatusEnum.SEI,
  },
  {
    value: 'TUSD',
    label: RequesSymbolEnum.TUSD,
    type: RequestStatusEnum.TUSD,
  },
  {
    value: 'MKR',
    label: RequesSymbolEnum.MKR,
    type: RequestStatusEnum.MKR,
  },
  {
    value: 'QNT',
    label: RequesSymbolEnum.QNT,
    type: RequestStatusEnum.QNT,
  },
  {
    value: 'BSV',
    label: RequesSymbolEnum.BSV,
    type: RequestStatusEnum.BSV,
  },
  {
    value: 'RETH',
    label: RequesSymbolEnum.RETH,
    type: RequestStatusEnum.RETH,
  },
  {
    value: 'ORDI',
    label: RequesSymbolEnum.ORDI,
    type: RequestStatusEnum.ORDI,
  },
  {
    value: 'GRT',
    label: RequesSymbolEnum.GRT,
    type: RequestStatusEnum.GRT,
  },
  {
    value: 'ALGO',
    label: RequesSymbolEnum.ALGO,
    type: RequestStatusEnum.ALGO,
  },
  {
    value: 'AAVE',
    label: RequesSymbolEnum.AAVE,
    type: RequestStatusEnum.AAVE,
  },
  {
    value: 'EGLD',
    label: RequesSymbolEnum.EGLD,
    type: RequestStatusEnum.EGLD,
  },
  {
    value: 'RNDR',
    label: RequesSymbolEnum.RNDR,
    type: RequestStatusEnum.RNDR,
  },
  {
    value: 'TAO',
    label: RequesSymbolEnum.TAO,
    type: RequestStatusEnum.TAO,
  },
  {
    value: 'RUNE',
    label: RequesSymbolEnum.RUNE,
    type: RequestStatusEnum.RUNE,
  },
  {
    value: 'SUI',
    label: RequesSymbolEnum.SUI,
    type: RequestStatusEnum.SUI,
  },
  {
    value: 'SATS',
    label: RequesSymbolEnum.SATS,
    type: RequestStatusEnum.SATS,
  },
  {
    value: 'MINA',
    label: RequesSymbolEnum.MINA,
    type: RequestStatusEnum.MINA,
  },
  {
    value: 'FLOW',
    label: RequesSymbolEnum.FLOW,
    type: RequestStatusEnum.FLOW,
  },
  {
    value: 'SNX',
    label: RequesSymbolEnum.SNX,
    type: RequestStatusEnum.SNX,
  },
  {
    value: 'FTM',
    label: RequesSymbolEnum.FTM,
    type: RequestStatusEnum.FTM,
  },
  {
    value: 'OSMO',
    label: RequesSymbolEnum.OSMO,
    type: RequestStatusEnum.OSMO,
  },
  {
    value: 'DYDX',
    label: RequesSymbolEnum.DYDX,
    type: RequestStatusEnum.DYDX,
  },
  {
    value: 'TKX',
    label: RequesSymbolEnum.TKX,
    type: RequestStatusEnum.TKX,
  },
  {
    value: 'AXS',
    label: RequesSymbolEnum.AXS,
    type: RequestStatusEnum.AXS,
  },
  {
    value: 'SAND',
    label: RequesSymbolEnum.SAND,
    type: RequestStatusEnum.SAND,
  },
  {
    value: 'HNT',
    label: RequesSymbolEnum.HNT,
    type: RequestStatusEnum.HNT,
  },
  {
    value: 'THETA',
    label: RequesSymbolEnum.THETA,
    type: RequestStatusEnum.THETA,
  },
  {
    value: 'BEAM',
    label: RequesSymbolEnum.BEAM,
    type: RequestStatusEnum.BEAM,
  },
  {
    value: 'BTT',
    label: RequesSymbolEnum.BTT,
    type: RequestStatusEnum.BTT,
  },
  {
    value: 'XTZ',
    label: RequesSymbolEnum.XTZ,
    type: RequestStatusEnum.XTZ,
  },
  {
    value: 'KCS',
    label: RequesSymbolEnum.KCS,
    type: RequestStatusEnum.KCS,
  },
  {
    value: 'WEMIX',
    label: RequesSymbolEnum.WEMIX,
    type: RequestStatusEnum.WEMIX,
  },
  {
    value: 'CHZ',
    label: RequesSymbolEnum.CHZ,
    type: RequestStatusEnum.CHZ,
  },
  {
    value: 'WBT',
    label: RequesSymbolEnum.WBT,
    type: RequestStatusEnum.WBT,
  },
  {
    value: 'ETHDYDX',
    label: RequesSymbolEnum.ETHDYDX,
    type: RequestStatusEnum.ETHDYDX,
  },
  {
    value: 'CHEEL',
    label: RequesSymbolEnum.CHEEL,
    type: RequestStatusEnum.CHEEL,
  },
  {
    value: 'EOS',
    label: RequesSymbolEnum.EOS,
    type: RequestStatusEnum.EOS,
  },
  {
    value: 'ASTR',
    label: RequesSymbolEnum.ASTR,
    type: RequestStatusEnum.ASTR,
  },
  {
    value: 'NEO',
    label: RequesSymbolEnum.NEO,
    type: RequestStatusEnum.NEO,
  },
  {
    value: 'BGB',
    label: RequesSymbolEnum.BGB,
    type: RequestStatusEnum.BGB,
  },
  {
    value: 'MANA',
    label: RequesSymbolEnum.MANA,
    type: RequestStatusEnum.MANA,
  },
  {
    value: 'BONK',
    label: RequesSymbolEnum.BONK,
    type: RequestStatusEnum.BONK,
  },
  {
    value: 'BLUR',
    label: RequesSymbolEnum.BLUR,
    type: RequestStatusEnum.BLUR,
  },
  {
    value: 'KAVA',
    label: RequesSymbolEnum.KAVA,
    type: RequestStatusEnum.KAVA,
  },
  {
    value: 'GALA',
    label: RequesSymbolEnum.GALA,
    type: RequestStatusEnum.GALA,
  },
  {
    value: 'ROSE',
    label: RequesSymbolEnum.ROSE,
    type: RequestStatusEnum.ROSE,
  },
  {
    value: 'KLAY',
    label: RequesSymbolEnum.KLAY,
    type: RequestStatusEnum.KLAY,
  },
  {
    value: 'FRXETH',
    label: RequesSymbolEnum.FRXETH,
    type: RequestStatusEnum.FRXETH,
  },
  {
    value: 'WOO',
    label: RequesSymbolEnum.WOO,
    type: RequestStatusEnum.WOO,
  },
  {
    value: 'IOTA',
    label: RequesSymbolEnum.IOTA,
    type: RequestStatusEnum.IOTA,
  },
  {
    value: 'LUNC',
    label: RequesSymbolEnum.LUNC,
    type: RequestStatusEnum.LUNC,
  },
  {
    value: 'CAKE',
    label: RequesSymbolEnum.CAKE,
    type: RequestStatusEnum.CAKE,
  },
  {
    value: 'USDD',
    label: RequesSymbolEnum.USDD,
    type: RequestStatusEnum.USDD,
  },
  {
    value: 'CFX',
    label: RequesSymbolEnum.CFX,
    type: RequestStatusEnum.CFX,
  },
  {
    value: 'FET',
    label: RequesSymbolEnum.FET,
    type: RequestStatusEnum.FET,
  },
];

export const RequestStatusEnumIndex: { [key: string]: RequestStatusEnum } = {
  BTC: RequestStatusEnum.BTC,
  ETH: RequestStatusEnum.ETH,
  USDT: RequestStatusEnum.USDT,
  BNB: RequestStatusEnum.BNB,
  SOL: RequestStatusEnum.SOL,
  XRP: RequestStatusEnum.XRP,
  USDC: RequestStatusEnum.USDC,
  STETH: RequestStatusEnum.STETH,
  ADA: RequestStatusEnum.ADA,
  AVAX: RequestStatusEnum.AVAX,
  DOGE: RequestStatusEnum.DOGE,
  DOT: RequestStatusEnum.DOT,
  TRX: RequestStatusEnum.TRX,
  LINK: RequestStatusEnum.LINK,
  TON: RequestStatusEnum.TON,
  MATIC: RequestStatusEnum.MATIC,
  WBTC: RequestStatusEnum.WBTC,
  ICP: RequestStatusEnum.ICP,
  SHIB: RequestStatusEnum.SHIB,
  DAI: RequestStatusEnum.DAI,
  LTC: RequestStatusEnum.LTC,
  UNI: RequestStatusEnum.UNI,
  BCH: RequestStatusEnum.BCH,
  ATOM: RequestStatusEnum.ATOM,
  ETC: RequestStatusEnum.ETC,
  LEO: RequestStatusEnum.LEO,
  INJ: RequestStatusEnum.INJ,
  XLM: RequestStatusEnum.XLM,
  OP: RequestStatusEnum.OP,
  NEAR: RequestStatusEnum.NEAR,
  OKB: RequestStatusEnum.OKB,
  APT: RequestStatusEnum.APT,
  TIA: RequestStatusEnum.TIA,
  LDO: RequestStatusEnum.LDO,
  FIL: RequestStatusEnum.FIL,
  XMR: RequestStatusEnum.XMR,
  IMX: RequestStatusEnum.IMX,
  HBAR: RequestStatusEnum.HBAR,
  ARB: RequestStatusEnum.ARB,
  KAS: RequestStatusEnum.KAS,
  CRO: RequestStatusEnum.CRO,
  STX: RequestStatusEnum.STX,
  MNT: RequestStatusEnum.MNT,
  VET: RequestStatusEnum.VET,
  FDUSD: RequestStatusEnum.FDUSD,
  SEI: RequestStatusEnum.SEI,
  TUSD: RequestStatusEnum.TUSD,
  MKR: RequestStatusEnum.MKR,
  QNT: RequestStatusEnum.QNT,
  BSV: RequestStatusEnum.BSV,
  RETH: RequestStatusEnum.RETH,
  ORDI: RequestStatusEnum.ORDI,
  GRT: RequestStatusEnum.GRT,
  ALGO: RequestStatusEnum.ALGO,
  AAVE: RequestStatusEnum.AAVE,
  EGLD: RequestStatusEnum.EGLD,
  RNDR: RequestStatusEnum.RNDR,
  TAO: RequestStatusEnum.TAO,
  RUNE: RequestStatusEnum.RUNE,
  SUI: RequestStatusEnum.SUI,
  SATS: RequestStatusEnum.SATS,
  MINA: RequestStatusEnum.MINA,
  FLOW: RequestStatusEnum.FLOW,
  SNX: RequestStatusEnum.SNX,
  FTM: RequestStatusEnum.FTM,
  OSMO: RequestStatusEnum.OSMO,
  DYDX: RequestStatusEnum.DYDX,
  TKX: RequestStatusEnum.TKX,
  AXS: RequestStatusEnum.AXS,
  SAND: RequestStatusEnum.SAND,
  HNT: RequestStatusEnum.HNT,
  THETA: RequestStatusEnum.THETA,
  BEAM: RequestStatusEnum.BEAM,
  BTT: RequestStatusEnum.BTT,
  XTZ: RequestStatusEnum.XTZ,
  KCS: RequestStatusEnum.KCS,
  WEMIX: RequestStatusEnum.WEMIX,
  CHZ: RequestStatusEnum.CHZ,
  WBT: RequestStatusEnum.WBT,
  ETHDYDX: RequestStatusEnum.ETHDYDX,
  CHEEL: RequestStatusEnum.CHEEL,
  EOS: RequestStatusEnum.EOS,
  ASTR: RequestStatusEnum.ASTR,
  NEO: RequestStatusEnum.NEO,
  BGB: RequestStatusEnum.BGB,
  MANA: RequestStatusEnum.MANA,
  BONK: RequestStatusEnum.BONK,
  BLUR: RequestStatusEnum.BLUR,
  KAVA: RequestStatusEnum.KAVA,
  GALA: RequestStatusEnum.GALA,
  ROSE: RequestStatusEnum.ROSE,
  KLAY: RequestStatusEnum.KLAY,
  FRXETH: RequestStatusEnum.FRXETH,
  WOO: RequestStatusEnum.WOO,
  IOTA: RequestStatusEnum.IOTA,
  LUNC: RequestStatusEnum.LUNC,
  CAKE: RequestStatusEnum.CAKE,
  USDD: RequestStatusEnum.USDD,
  CFX: RequestStatusEnum.CFX,
  FET: RequestStatusEnum.FET,
};
